port: 4002

title: "Monthly Correspondence: Notes" 
email: <insertnamehere>@mail.com
description: > # this means to ignore newlines until "baseurl:"   
  Monthly Correspondence is a web journal for publishing Jupyter notebooks with full open reviews. 
  The entire processes of submission and review is handled by github. A submission is initially made via a pull request. 
  Then reviewing is interactive and handled by commenting on the resulting pull request. 

  The notebook review process will therefore be open and any github user will be able to comment. 

  Each notebook will have an initial editor assigned, but anyone can chime
  in and comment or suggest edits. Acceptance of the submission occurs when the pull request is accepted.

baseurl: "" # the subpath of your site, e.g. /blog 
url: "" # the base hostname & protocol for your site, e.g. http://example.com #

twitter_username: jekyllrb 
github_username:  mzwiessele 
repository: MC-Notes/mc-notes.github.io

# Permalinks
permalink: /:year/:month/:day/:title/

# Build settings
gems:
- jekyll-autoprefixer
- jekyll-pandoc
- pandoc-ruby
- github-pages
- git
- safe_yaml

markdown: redcarpet #kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - "node_modules"
  - "gulpfile.js"
  - "package.json"
  - cacert.pem
  - serve
  - README.md
  # - NOTES.md

# Package settings:
autoprefixer:
  browsers: ['last 15 versions', '> 1%', 'ie 8', 'ie 7']